### ISSUE TITLE
Media and saving issues

### ISSUE THREAD

**Issue by mariamuradas** [olivierfriard/BORIS#284]
I am using BORIS version 7.9.8 in a MacBook Pro with MacOS Mojave 10.14.6 and I am having multiple issues:

1. Audio plays/ screen black. I can fix it with on/off the frame by frame button.
2. The video image changes sizes/zoom by itself in the window. This happens always that you open the coding pad.
3. It crashes when trying to save changes in the ethogram and/or observations. Some times it even loses data already saved.
4. The program closes when you close an observation. The computer reports it as an unexpected closure.

**Comment by loganwhiles** [comment]
My group is also experiencing issue #4 on Mac, and seemingly some other similar saving issues. So far, we've been doing our best to resolve this by repeatedly selecting "save" in the dropdown menu (shortcut doesn't seem to be as reliable) and occasionally saving backups. I have also found it helpful to go to my Observation List rather than closing the observation directly. It tends to allow me to close the observation that way. Then I cancel out of the observation list and save again. All this is to say I second this issue, and am eager to hear any workarounds.

Thanks mariamuradas.

**Comment by olivierfriard** [comment]
Hi,
I just released the v. 7.9.13 (pre-release for now): https://github.com/olivierfriard/BORIS/releases/tag/v7.9.13
This version should save information about the crash in a file in order to improve the program stability. The file is named boris_error.log and is located in your home directory (/Users/YOUR_PROFILE_NAME/boris_error.log). Please use this version and send me by email the file generated after every crash.
Thank you for your collaboration.
o
