### ISSUE TITLE
Plot events with separate observations

### ISSUE THREAD

**Issue by gpwakeford** [olivierfriard/BORIS#286]
I don't know if this is documented elsewhere, but I was wondering if it was possible to create an event plot that displayed events from multiple different observations on one log? 

For example, I have four observations in that include two subjects per observation, but they are not the same 2 subjects in all four observations. What I'd like is to create an event log that has all 8 subjects' events recorded even though they were taken from different observations. 

Is this possible? I'm attaching a pdf of an event log that has all of the subjects listed, but only displays the actual events of 2 animals. 

Thanks
[ec_09_11.pdf](https://github.com/olivierfriard/BORIS/files/4730821/ec_09_11.pdf)

**Comment by gpwakeford** [comment]
Thanks for the quick response! Does it matter which video file these observations are attached to? For instance, if I copy and paste 3 observations worth of events into a new observation, does it matter that I'll be using a video that doesn't have those subjects in it?

**Comment by olivierfriard** [comment]
It does not matter because it will be a dummy observation.
If you do not want to select a dummy video choose "Live observation".

o

University of Torino
Life Sciences and Systems Biology department
Via dell'Accademia Albertina, 13 10123 TORINO (Italy)
tel: +39 011 6704542
http://penelope.unito.it/friard/
http://orcid.org/0000-0002-0374-9872

**Comment by gpwakeford** [comment]
Got it, thank you so much!
