### ISSUE TITLE
Scan sampling on media files?

### ISSUE THREAD

**Issue by eagreg** [olivierfriard/BORIS#301]
Hello! 
I'm wanting to use BORIS for a behavioural analyses combining continuous and scan sampling techniques. Following the guide I see that I can do this live; https://boris.readthedocs.io/en/latest/#scan-sampling. However, is this possible on media files? 
Many thanks!

**Comment by olivierfriard** [comment]
Hello,

you can pause your video and use the fast forward/backward buttons:
https://boris.readthedocs.io/en/latest/#media-based-coding

o

**Comment by eagreg** [comment]
Hi Olivier,

Thank you for your guidance, we were hoping to use the Scan sampling function on media for the accuracy it offers.
We will most likely set the ‘beep’ at a predetermined time interval to alert to complete a behavioural observation.
It would be great to see scan sampling as a preference for media files in future versions as the automatic pause is rather helpful!

Many thanks,
Emily

**Comment by StephPeriquet** [comment]
I want to do the same thing on macOS Big Sur and the issue is that when I use the  fast forward/backward buttons the frame doesn't change every single time. Sometimes it does, sometimes it doesn't...
The trick I found to make it work is got into the frame by frame mode, and then it works like a charm!
