### ISSUE TITLE
Unable to install BORIS v.8 on Ubuntu 20.04

### ISSUE THREAD

**Issue by RafaelSBessa** [olivierfriard/BORIS#408]
Hi, I tried to install  BORIS v.8 by double clicking in the 'start_boris' file. The Ubuntu Software opened but displayed the following message: 'Failed to install: Not supported'

I then tried to install via terminal and got the following message and error log:

./start_boris, line 16:  8276 Aborted                (core dumped) "$DIR/bin/python3" -E -m boris -d stdout "$@" > "$HOME/boris_error.log" 2>&1

[boris_error.log](https://github.com/olivierfriard/BORIS/files/6711358/boris_error.log)

Could you help me?

**Comment by olivierfriard** [comment]
Hi,

the problem should be fixed with the v. 8.0.10 (https://github.com/olivierfriard/BORIS/releases/tag/v8.0.10)
Download the .deb file and double-click on it (it should start with the software install application).
If not you can use the following command from a terminal:
sudo apt install ./boris_8.0.10-0.deb

You should find BORIS in the Education menu (or equivalent)

Please let me know if your issue is fixed

Best,

Olivier

**Comment by RafaelSBessa** [comment]
Hi Olivier,

I downloaded v. 8.0.10 and it worked !!

Thank you very much.
