### ISSUE TITLE
No observations in version 8.5

### ISSUE THREAD

**Issue by Sarah2022A** [olivierfriard/BORIS#496]
Hi Olivier 

Looking forward to trying out version 8.5 but having an issue with accessing observations. I opened up the project I was using with version 8.014, then go to open an observation (observations>start observation), nothing happens - no selection window appears. When go to view observations (observations>view observation) I can see that yes they are all there. I can also create an observation - but that doesn't open either. When I select file>edit project, there is no "observations" tab visible (see screen shot). 

I am using windows 10. 

Cheers
![Screenshot 2022-06-06 162540](https://user-images.githubusercontent.com/57016893/172094739-41c190c9-ab03-43a1-9102-494b97de27ad.jpg)

**Comment by olivierfriard** [comment]
Hi Sarah,

thank you for reporting this.
It is just a "little" bug (already fixed in the next release). To start an observation you can open the observation's list, select the observation and press the Start button.

The Observations tab is no more present in the project window because the observations can be removed from the Observations menu.

Cheers
