### ISSUE TITLE
How to set the start time of observation when observing media files

### ISSUE THREAD

**Issue by Avianalh** [olivierfriard/BORIS#540]
For example, when observing the event, the first feeding behavior of the animal occurred in 2022/10/11/10:20, ended in 2022/10/11/10:25, and the subsequent behavior occurred successively. How to record the data in this form？

We are looking forward to your reply. Thank you

**Comment by olivierfriard** [comment]
Hi,

it is not possible directly in BORIS but you can use the following workaround:

1) add an offset time to your observation. This offset should correspond to the Unix Epoch time (number of seconds since 1970-01-01 00:00:00) of the beginning of your recording. See https://en.wikipedia.org/wiki/Unix_time and https://www.epochconverter.com for details.

2) Convert the Unix epoch time in date time format on the results file with Excel. See https://www.exceldemy.com/convert-epoch-time-to-date-excel/

I hope this will help you
