### ISSUE TITLE
dock video frame, time format

### ISSUE THREAD

**Issue by simonisl** [olivierfriard/BORIS#89]
Good afternoon,

I have two questions: 
1) How can video frames be docked again? I read the user manual and found out that all frames can be undocked, so I tried (as a matter of interest) and could re-dock all frames afterwards but the video frame. I closed the observation and also the project, opened another project but still the same problem: the video frames opens in VLC (Direct3d output).

2) The time format exported is always in seconds - no matter if "seconds" or "hh:mm:ss:mss") is set under "preferences" or within the current observation. As I have some videos over 90 minutes it's very unpractical to read it in seconds in my Excel sheets. Is there any way to export the time in hh:mm:ss (I do not even need mss)? Is there a way to export the following data in one (!) Excel: indipendent variables, key, code, category, start, end, duration. I can't find any possibility to select the variables I would like to export.

Thank you again!

**Comment by olivierfriard** [comment]
Hello,

1. See File > Preferences > Project tab > Embed media player in main window...
For frame-by-frame mode:
File > Preferences > Frame-by-frame tab > Detach frame viewer

Please tell me if your problem is fixed.

2. You can convert time in seconds in hh:mm:ss format in Excel with a formula:
See https://answers.microsoft.com/en-us/msoffice/forum/msoffice_excel-mso_other/convert-seconds-into-hhmmss-format/3d01802b-57f4-4a30-ae7d-3e0fb2c5ea7c?auth=1 for details

**Comment by spookworm** [comment]
it would be important to export in milliseconds for rapid actions though, is this not possible?
